version: '3.5'

services:
#  postgres:
#    image: postgres
#    restart: always
#    environment:
#      - POSTGRES_PASSWORD=postgres
#    container_name: postgres
#    volumes:
#      - ./pgdata:/var/lib/postgresql/data
#    ports:
#      - '5432:5432'
#    networks: [blockchain]

  redis:
    image: bitnami/redis
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 15s
      retries: 30
    ports: 
      - 6379:6379
    environment:
      REDIS_PASSWORD: "test"
      ALLOW_EMPTY_PASSWORD: "yes"
    networks: [blockchain]

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: blockchain-backend
    environment:
      - PORT=3000:3000
      - REDIS_=redis
    command: npm run start:debug
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      - redis
#      - postgres
    volumes:
      - '.:/app'
      - './node_modules:/app/node_modules'
    networks: [blockchain]


#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    container_name: nest-pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#    ports:
#      - '5050:80'
#    depends_on:
#      - postgres
#    networks: [blockchain]

networks:
    blockchain: ~
